on:
  workflow_dispatch:

name: Check Venue Statuses

permissions:
  contents: read

jobs:
  check_cineworld:
    name: Check Cineworld
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
      - run: node scripts/check-cineworld-ids.js

  check_curzon:
    name: Check Curzon
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
        with:
          playwright: true
      - run: node scripts/check-curzon-ids.js

  check_everyman:
    name: Check Everyman
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
      - run: node scripts/check-everyman-ids.js

  check_myvue:
    name: Check Vue
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
      - run: node scripts/check-myvue-ids.js

  check_odeon:
    name: Check Odeon
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
        with:
          playwright: true
      - run: node scripts/check-odeon-ids.js

  check_omniplex:
    name: Check Omniplex
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
      - run: node scripts/check-omniplex-ids.js

  check_picturehouse:
    name: Check Picturehouse
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: clusterflick/.github/setup@main
        with:
          playwright: true
      - run: node scripts/check-picturehouse-ids.js
