on:
  workflow_dispatch:
  repository_dispatch:
    types: [compare_releases]

name: Compare Accessible Screenings

jobs:
  compare:
    name: Compare Accessible Screenings
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - run: npm install
      - uses: clusterflick/release-downloader@v3
        with:
          token: ${{ secrets.PAT }}
          repository: "clusterflick/data-transformed"
          latest: true
          fileName: "*"
          out-file-path: "transformed-data"

      - name: Download UKCA data
        run: npm run download:accessible-screenings

      - name: Compare accessible screenings
        run: npm run compare:accessible-screenings -- accessible-screenings-data/ukca-data.json transformed-data

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: accessible-screenings-report
          path: output/
          retention-days: 14
